package main

import (
	"encoding/json"
	"fmt"
	"strings"
)

// controversyLabel returns an ordinal label factoring in effective sample size.
func controversyLabel(score float64, nAgree, nDisagree int) string {
	total := nAgree + nDisagree
	if total <= 2 {
		return "Divided (small N)"
	}
	switch {
	case score >= 0.9:
		return "Sharp division"
	case score >= 0.7:
		return "Strong disagreement"
	case score >= 0.55:
		return "Moderate disagreement"
	case score >= 0.4:
		return "Contested"
	default:
		return "Mild disagreement"
	}
}

func isStructuralAgent(id string) bool {
	return strings.Contains(id, "probe") ||
		strings.Contains(id, "adversary") ||
		strings.Contains(id, "bridge") ||
		strings.Contains(id, "dissent") ||
		strings.Contains(id, "empty-chair") ||
		strings.Contains(id, "resolution")
}

func generateReport(ri *reportInput) string {
	data := ri.Data
	agents := ri.R1Agents
	r2Agents := ri.R2Agents
	r3Agents := ri.R3Agents
	r2JSON := ri.R2JSON
	r3JSON := ri.R3JSON
	r1Compromise := ri.R1Compromise
	r2Compromise := ri.R2Compromise
	r3Compromise := ri.R3Compromise
	tmpl := ri.Template
	delibID := ri.DelibID
	joinCode := ri.JoinCode
	ncResult := ri.NullControl
	scResult := ri.SpotCheck
	repResult := ri.Replication
	covResult := ri.Coverage
	vfResult := ri.Verify

	var r1 analysisResult
	json.Unmarshal([]byte(ri.R1JSON), &r1)

	var r2 analysisResult
	if ri.R2JSON != "" {
		json.Unmarshal([]byte(ri.R2JSON), &r2)
	}

	var r3 analysisResult
	if ri.R3JSON != "" {
		json.Unmarshal([]byte(ri.R3JSON), &r3)
	}

	var b strings.Builder

	// Header — prominent provenance
	fmt.Fprintf(&b, "# Gemot Deliberation Report: %s\n\n", data.Title)
	b.WriteString("> **Provenance**: This report was generated by importing a [Talk to the City](https://talktothe.city) report into gemot's structural deliberation pipeline. ")
	b.WriteString("All agents are AI-synthesized from T3C's extracted claims — they represent discourse topology, not real participants. ")
	b.WriteString("Crux scores reflect synthetic agent agreement patterns, not human expert consensus. ")
	b.WriteString("Substantive conclusions should be verified against primary sources before any policy or governance use.\n\n")

	fmt.Fprintf(&b, "Deliberation: `%s`", delibID)
	if joinCode != "" {
		fmt.Fprintf(&b, " · Join: `%s`", joinCode)
	}
	repTier := "Tier 0 (single run — unreplicated)"
	if repResult != nil && len(repResult.Runs) >= 2 {
		s := repResult.Stability
		if s.Tier == 2 {
			repTier = fmt.Sprintf("Tier 2 (%d runs, all CV < 0.2)", len(repResult.Runs))
		} else {
			repTier = fmt.Sprintf("Tier 1 (%d runs)", len(repResult.Runs))
		}
	}
	fmt.Fprintf(&b, " · Template: %s · Replication: **%s**\n\n", tmpl, repTier)

	// Source report
	totalClaims := countClaims(data)
	b.WriteString("## Source Report\n\n")
	fmt.Fprintf(&b, "- %d topics, %d claims, %d speakers\n", len(data.Topics), totalClaims, len(data.Sources))
	if data.AddOns != nil {
		fmt.Fprintf(&b, "- %d cruxes in T3C report\n", len(data.AddOns.SubtopicCruxes))
	}
	b.WriteString("\n")

	// Stance verification
	if vfResult != nil && vfResult.Checked > 0 {
		b.WriteString("## Stance Verification\n\n")
		kept := vfResult.Checked - vfResult.Downgraded
		fmt.Fprintf(&b, "*%d stances checked against source quotes (1-5 grounding scale). %d kept (score 4-5), %d downgraded to no_position (score 1-3).*\n\n", vfResult.Checked, kept, vfResult.Downgraded)

		// Score distribution
		b.WriteString("| Score | Meaning | Count |\n")
		b.WriteString("|---|---|---|\n")
		labels := [6]string{"", "No relevant quotes", "Tangentially related", "Interpretation", "Clearly aligned", "Explicitly supported"}
		for s := 5; s >= 1; s-- {
			marker := ""
			if s <= 3 {
				marker = " *(downgraded)*"
			}
			fmt.Fprintf(&b, "| %d | %s | %d%s |\n", s, labels[s], vfResult.ScoreDist[s], marker)
		}
		b.WriteString("\n")

		if len(vfResult.Details) > 0 {
			b.WriteString("**Downgraded stances:**\n")
			for _, d := range vfResult.Details {
				fmt.Fprintf(&b, "- **%s** (%s, score %d) on: %s\n", d.Speaker, d.OrigStance, d.Score, d.Crux)
				if d.Reason != "" {
					fmt.Fprintf(&b, "  - %s\n", d.Reason)
				}
			}
			b.WriteString("\n")
		}
	}

	// Participants
	b.WriteString("## Participants\n\n")
	b.WriteString("Agents fall into two categories: **speaker-derived** (grounded in named speakers' extracted claims) and **structural** (pipeline-generated to probe the discourse topology). Crux scores are reported separately for each category.\n\n")

	var steelmen, speakers, probes []agentPlan
	for _, a := range agents {
		switch a.Kind {
		case "steelman":
			steelmen = append(steelmen, a)
		case "speaker":
			speakers = append(speakers, a)
		case "probe":
			probes = append(probes, a)
		}
	}

	nSpeakerDerived := len(steelmen) + len(speakers)
	nStructural := len(probes) + len(r2Agents)
	nRevised := len(r3Agents)

	if len(steelmen) > 0 {
		b.WriteString("**Clusters** (speakers grouped by ≥70% agreement across crux stances):\n")
		for _, a := range steelmen {
			fmt.Fprintf(&b, "- %s\n", a.Role)
		}
		b.WriteString("\n")
	}
	if len(speakers) > 0 {
		b.WriteString("**Speakers** (singletons — not clustered with others):\n")
		for _, a := range speakers {
			fmt.Fprintf(&b, "- %s\n", a.Role)
		}
		b.WriteString("\n")
	}
	if len(probes) > 0 {
		b.WriteString("**Topic Probes** *(structural)*:\n")
		for _, a := range probes {
			fmt.Fprintf(&b, "- %s\n", a.Role)
		}
		b.WriteString("\n")
	}
	if len(r2Agents) > 0 {
		b.WriteString("**Round 2 Agents** *(structural — informed by R1 analysis)*:\n")
		for _, a := range r2Agents {
			fmt.Fprintf(&b, "- %s (%s)\n", a.Role, a.Kind)
		}
		b.WriteString("\n")
	}
	if len(r3Agents) > 0 {
		b.WriteString("**Round 3 Agents** *(revised positions — informed by R2 analysis)*:\n")
		for _, a := range r3Agents {
			fmt.Fprintf(&b, "- %s\n", a.Role)
		}
		b.WriteString("\n")
	}
	if nRevised > 0 {
		fmt.Fprintf(&b, "*Pool composition: %d speaker-derived, %d structural, %d revised agents*\n\n", nSpeakerDerived, nStructural, nRevised)
	} else {
		fmt.Fprintf(&b, "*Pool composition: %d speaker-derived, %d structural agents*\n\n", nSpeakerDerived, nStructural)
	}

	// Round 1
	b.WriteString("## Round 1: Initial Analysis\n\n")
	writeAnalysis(&b, &r1, r1Compromise, nSpeakerDerived, nStructural)

	// Round 2
	if r2JSON != "" {
		b.WriteString("## Round 2: Emergent Findings\n\n")
		writeAnalysis(&b, &r2, r2Compromise, nSpeakerDerived, nStructural+len(r2Agents))

		// Evolution
		b.WriteString("## Evolution\n\n")
		newCruxes := findNewCruxes(r1.Cruxes, r2.Cruxes)
		if len(newCruxes) > 0 {
			b.WriteString("**New or refined cruxes in Round 2:**\n")
			for _, c := range newCruxes {
				label := controversyLabel(c.Score, c.NAgree, c.NDisagree)
				fmt.Fprintf(&b, "- [%s] %s\n", label, c.Claim[:min(140, len(c.Claim))])
			}
			b.WriteString("\n*R2 cruxes may be reworded versions of R1 cruxes. Exact string matching identifies new cruxes — some may be refinements.*\n\n")
		}

		// Topic stability (using stable topic IDs where available)
		r1TopicsByID := map[string]string{}  // ID → name
		r1TopicsByName := map[string]bool{}
		for _, ts := range r1.TopicSummaries {
			r1TopicsByName[ts.Topic] = true
			if ts.TopicID != "" {
				r1TopicsByID[ts.TopicID] = ts.Topic
			}
		}
		var newTopics, droppedTopics, renamedTopics []string
		r2TopicsByID := map[string]string{}
		r2TopicsByName := map[string]bool{}
		for _, ts := range r2.TopicSummaries {
			r2TopicsByName[ts.Topic] = true
			if ts.TopicID != "" {
				r2TopicsByID[ts.TopicID] = ts.Topic
			}
			// Check if this is a new topic or a renamed one
			if ts.TopicID != "" {
				if r1Name, ok := r1TopicsByID[ts.TopicID]; ok && r1Name != ts.Topic {
					renamedTopics = append(renamedTopics, fmt.Sprintf("%s: %s → %s", ts.TopicID, r1Name, ts.Topic))
				}
			}
			if !r1TopicsByName[ts.Topic] {
				isRenamed := false
				if ts.TopicID != "" {
					_, isRenamed = r1TopicsByID[ts.TopicID]
				}
				if !isRenamed {
					label := ts.Topic
					if ts.TopicID != "" {
						label = ts.TopicID + ": " + ts.Topic
					}
					newTopics = append(newTopics, label)
				}
			}
		}
		for _, ts := range r1.TopicSummaries {
			if !r2TopicsByName[ts.Topic] {
				isRenamed := false
				if ts.TopicID != "" {
					_, isRenamed = r2TopicsByID[ts.TopicID]
				}
				if !isRenamed {
					label := ts.Topic
					if ts.TopicID != "" {
						label = ts.TopicID + ": " + ts.Topic
					}
					droppedTopics = append(droppedTopics, label)
				}
			}
		}
		if len(newTopics) > 0 || len(droppedTopics) > 0 || len(renamedTopics) > 0 {
			b.WriteString("**Topic taxonomy changes:**\n")
			if len(renamedTopics) > 0 {
				fmt.Fprintf(&b, "- Renamed: %s\n", strings.Join(renamedTopics, "; "))
			}
			if len(newTopics) > 0 {
				fmt.Fprintf(&b, "- New in R2: %s\n", strings.Join(newTopics, ", "))
			}
			if len(droppedTopics) > 0 {
				fmt.Fprintf(&b, "- Dropped from R1: %s\n", strings.Join(droppedTopics, ", "))
			}
			b.WriteString("*Topic IDs (T1, T2, ...) persist across rounds. R2 receives R1 topic names as guidance; renamed topics share the same ID.*\n\n")
		}
	}

	// Round 3
	if r3JSON != "" {
		b.WriteString("## Round 3: Revised Positions\n\n")
		b.WriteString("*Speaker-derived agents revised their positions after seeing R2 findings. Revisions are LLM-generated, constrained to what the speaker's stated views would plausibly accommodate.*\n\n")
		writeAnalysis(&b, &r3, r3Compromise, nSpeakerDerived, nStructural+nRevised)

		// Position evolution
		if len(r3Agents) > 0 {
			b.WriteString("### Position Evolution\n\n")
			for _, r3a := range r3Agents {
				originalID := strings.TrimSuffix(r3a.ID, "-r3")
				// Find original R1 agent
				for _, r1a := range agents {
					if r1a.ID == originalID {
						fmt.Fprintf(&b, "**%s**:\n", r1a.Role)
						fmt.Fprintf(&b, "- *R1*: %s\n", firstLine(r1a.Position))
						fmt.Fprintf(&b, "- *R3*: %s\n\n", firstLine(r3a.Position))
						break
					}
				}
			}
		}
	}

	// Discarded cruxes — retained for diagnostic transparency
	allDiscarded := r1.DiscardedCruxes
	if r2JSON != "" {
		allDiscarded = append(allDiscarded, r2.DiscardedCruxes...)
	}
	if r3JSON != "" {
		allDiscarded = append(allDiscarded, r3.DiscardedCruxes...)
	}
	if len(allDiscarded) > 0 {
		b.WriteString("## Discarded Cruxes\n\n")
		b.WriteString("*These cruxes were generated but had no agents on one side after validation. Retained for diagnostic transparency.*\n\n")
		for _, c := range allDiscarded {
			emptySide := "agree"
			if len(c.Agree) > 0 {
				emptySide = "disagree"
			}
			failureMode := "agent pool gap"
			claim := strings.ToLower(c.Claim)
			if strings.Contains(claim, "inevitably") || strings.Contains(claim, "impossible") ||
				strings.Contains(claim, "will always") || strings.Contains(claim, "can never") {
				failureMode = "crux over-specified"
			}
			fmt.Fprintf(&b, "- **%s** (empty: %s side · likely: %s)\n", c.Claim[:min(100, len(c.Claim))], emptySide, failureMode)
		}
		b.WriteString("\n")
	}

	// Integrity warnings (excluding DEGENERATE since we show those above)
	var warnings []string
	for _, w := range r1.IntegrityWarnings {
		if !strings.HasPrefix(w, "DEGENERATE:") {
			warnings = append(warnings, w)
		}
	}
	if r2JSON != "" {
		for _, w := range r2.IntegrityWarnings {
			if !strings.HasPrefix(w, "DEGENERATE:") {
				warnings = append(warnings, w)
			}
		}
	}
	if r3JSON != "" {
		for _, w := range r3.IntegrityWarnings {
			if !strings.HasPrefix(w, "DEGENERATE:") {
				warnings = append(warnings, w)
			}
		}
	}
	if len(warnings) > 0 {
		b.WriteString("## Integrity\n\n")
		for _, w := range warnings {
			fmt.Fprintf(&b, "- %s\n", w)
		}
		b.WriteString("\n")
	}

	// Null control comparison
	if ncResult != nil {
		b.WriteString("## Null Control\n\n")
		b.WriteString("A null control was run by shuffling speaker-crux assignments (destroying real agreement patterns) while keeping the same claims. ")
		b.WriteString("If the pipeline finds similar structure in shuffled data, the real findings may be indistinguishable from noise.\n\n")
		b.WriteString("| Metric | Real Run | Null Control | Delta |\n")
		b.WriteString("|---|---|---|---|\n")
		realM := ncResult.RealMetrics
		nullM := ncResult.NullMetrics
		fmt.Fprintf(&b, "| Cruxes found | %d | %d | %s |\n", realM.CruxCount, nullM.CruxCount, metricDelta(realM.CruxCount, nullM.CruxCount))
		fmt.Fprintf(&b, "| Avg controversy | %.2f | %.2f | %s |\n", realM.AvgControversy, nullM.AvgControversy, metricDeltaFloat(realM.AvgControversy, nullM.AvgControversy))
		fmt.Fprintf(&b, "| Consensus statements | %d | %d | %s |\n", realM.ConsensusCount, nullM.ConsensusCount, metricDelta(realM.ConsensusCount, nullM.ConsensusCount))
		fmt.Fprintf(&b, "| Bridging proposals | %d | %d | %s |\n", realM.BridgingCount, nullM.BridgingCount, metricDelta(realM.BridgingCount, nullM.BridgingCount))
		fmt.Fprintf(&b, "| Clusters | %d | %d | %s |\n", realM.ClusterCount, nullM.ClusterCount, metricDelta(realM.ClusterCount, nullM.ClusterCount))
		fmt.Fprintf(&b, "| Confidence | %s | %s | — |\n\n", realM.Confidence, nullM.Confidence)
		if ncResult.Pass {
			b.WriteString("**Verdict:** Real run shows substantially different structure from null control. Findings are distinguishable from baseline noise.\n\n")
		} else {
			fmt.Fprintf(&b, "**Verdict:** Real run patterns are within 15%% of null control on %d metrics. Findings may be indistinguishable from noise.\n\n", len(ncResult.FailedMetrics))
			for _, f := range ncResult.FailedMetrics {
				fmt.Fprintf(&b, "- %s\n", f)
			}
			b.WriteString("\n")
		}
		fmt.Fprintf(&b, "*Null control deliberation: `%s`*\n\n", ncResult.NullDelibID)
	}

	// Coverage audit
	if covResult != nil && len(covResult.Gaps) > 0 {
		b.WriteString("## Missing Perspectives\n\n")
		b.WriteString("*Automatically detected absent viewpoints that would likely challenge unchallenged or lopsided positions.*\n\n")
		for _, gap := range covResult.Gaps {
			fmt.Fprintf(&b, "- **%s**\n", gap.Position)
			if gap.MissingPerspective != "" {
				fmt.Fprintf(&b, "  - Missing: %s\n", gap.MissingPerspective)
			}
			if gap.SuggestedSource != "" {
				fmt.Fprintf(&b, "  - Would contest: %s\n", gap.SuggestedSource)
			}
		}
		b.WriteString("\n")
	}

	// Replication results
	if repResult != nil && len(repResult.Runs) >= 2 {
		b.WriteString("## Replication\n\n")
		fmt.Fprintf(&b, "%d replication runs with identical input (same agents, same votes — only LLM analysis varies).\n\n", len(repResult.Runs))
		b.WriteString("| Run | Cruxes | Avg Controversy | Consensus | Bridging | Confidence |\n")
		b.WriteString("|---|---|---|---|---|---|\n")
		for i, r := range repResult.Runs {
			fmt.Fprintf(&b, "| %d | %d | %.2f | %d | %d | %s |\n",
				i+1, r.CruxCount, r.AvgControversy, r.ConsensusCount, r.BridgingCount, r.Confidence)
		}
		s := repResult.Stability
		fmt.Fprintf(&b, "\n**Stability (CV):** crux count %.2f, controversy %.2f, consensus %.2f\n", s.CruxCV, s.ControvCV, s.ConsensusCV)
		if s.AllStable {
			b.WriteString("\nAll metrics stable (CV < 0.2). Findings are reproducible.\n\n")
		} else {
			b.WriteString("\nSome metrics show high variance (CV >= 0.2). Findings should be interpreted with caution.\n\n")
		}
	}

	// Spot-check details
	if scResult != nil && len(scResult.Failed) > 0 {
		b.WriteString("## Spot-Check Failures\n\n")
		b.WriteString("*These stance assignments failed LLM verification against the speaker's source quotes.*\n\n")
		for _, f := range scResult.Failed {
			fmt.Fprintf(&b, "- **%s** classified as *%s*: %s\n", f.Speaker, f.Stance, f.Crux)
			if f.Verdict != "" {
				verdict := f.Verdict
				if len(verdict) > 200 {
					verdict = verdict[:197] + "..."
				}
				fmt.Fprintf(&b, "  - Reason: %s\n", verdict)
			}
		}
		b.WriteString("\n")
	}

	// Multi-threshold cluster stability
	if data.AddOns != nil && data.AddOns.SpeakerCruxMatrix != nil {
		mtc := multiThresholdClusters(data.AddOns.SpeakerCruxMatrix)
		if len(mtc) == 3 {
			b.WriteString("## Cluster Stability\n\n")
			b.WriteString("Cluster membership at multiple similarity thresholds. Clusters that dissolve above 80% are threshold-sensitive.\n\n")
			b.WriteString("| Threshold | Total Clusters | Multi-member |\n")
			b.WriteString("|---|---|---|\n")
			for _, t := range mtc {
				fmt.Fprintf(&b, "| %.0f%% | %d | %d |\n", t.Threshold*100, t.NumClusters, t.NumMulti)
			}
			if mtc[0].NumMulti > 0 && mtc[1].NumMulti == 0 {
				b.WriteString("\n*All multi-member clusters dissolve above 80% — groupings are threshold-sensitive.*\n")
			} else if mtc[0].NumMulti > mtc[1].NumMulti {
				dissolved := mtc[0].NumMulti - mtc[1].NumMulti
				fmt.Fprintf(&b, "\n*%d cluster(s) dissolve between 70%% and 80%% — these groupings are threshold-sensitive.*\n", dissolved)
			}
			b.WriteString("\n")
		}
	}

	// Reliability panel — replaces "Confidence: high"
	b.WriteString("## Reliability\n\n")
	degenerateRate := 0
	totalCruxGenerated := len(r1.Cruxes) + len(r1.DiscardedCruxes)
	if r2JSON != "" {
		totalCruxGenerated += len(r2.Cruxes) + len(r2.DiscardedCruxes)
	}
	if r3JSON != "" {
		totalCruxGenerated += len(r3.Cruxes) + len(r3.DiscardedCruxes)
	}
	if totalCruxGenerated > 0 {
		degenerateRate = (len(allDiscarded) * 100) / totalCruxGenerated
	}

	coherenceLabel := "pass"
	if degenerateRate > 40 {
		coherenceLabel = "fail"
	} else if degenerateRate > 20 {
		coherenceLabel = "partial"
	}

	// Count hallucination corrections for tiered severity
	hallucinationCount := 0
	for _, w := range r1.IntegrityWarnings {
		if strings.HasPrefix(w, "HALLUCINATION:") {
			hallucinationCount++
		}
	}
	if r2JSON != "" {
		for _, w := range r2.IntegrityWarnings {
			if strings.HasPrefix(w, "HALLUCINATION:") {
				hallucinationCount++
			}
		}
	}
	if r3JSON != "" {
		for _, w := range r3.IntegrityWarnings {
			if strings.HasPrefix(w, "HALLUCINATION:") {
				hallucinationCount++
			}
		}
	}

	correctionLabel := "none"
	correctionDetail := "No phantom agents removed"
	switch {
	case hallucinationCount >= 10:
		correctionLabel = "high"
		correctionDetail = fmt.Sprintf("%d phantom agents removed — manual audit recommended", hallucinationCount)
	case hallucinationCount >= 4:
		correctionLabel = "moderate"
		correctionDetail = fmt.Sprintf("%d phantom agents removed — affected cruxes flagged above", hallucinationCount)
	case hallucinationCount >= 1:
		correctionLabel = "minor"
		correctionDetail = fmt.Sprintf("%d phantom agent(s) removed", hallucinationCount)
	}

	fmt.Fprintf(&b, "| Dimension | Status | Detail |\n")
	fmt.Fprintf(&b, "|---|---|---|\n")
	fmt.Fprintf(&b, "| Internal coherence | %s | %d/%d cruxes survived validation (%d%% degenerate discard rate) |\n",
		coherenceLabel, totalCruxGenerated-len(allDiscarded), totalCruxGenerated, degenerateRate)
	fmt.Fprintf(&b, "| Agent hallucinations | %s | %s |\n", correctionLabel, correctionDetail)
	if vfResult != nil {
		vfLabel := "pass"
		kept := vfResult.Checked - vfResult.Downgraded
		vfDetail := fmt.Sprintf("All %d stances scored 4-5 against source quotes", vfResult.Checked)
		if vfResult.Downgraded > 0 {
			vfLabel = "cleaned"
			vfDetail = fmt.Sprintf("%d/%d kept (score 4-5), %d downgraded (score 1-3)", kept, vfResult.Checked, vfResult.Downgraded)
		}
		fmt.Fprintf(&b, "| Stance grounding | %s | %s |\n", vfLabel, vfDetail)
	}
	if ncResult != nil {
		ncLabel := "pass"
		ncDetail := "Real run distinguishable from shuffled null control"
		if !ncResult.Pass {
			ncLabel = "fail"
			ncDetail = fmt.Sprintf("%d metrics indistinguishable from noise", len(ncResult.FailedMetrics))
		}
		fmt.Fprintf(&b, "| Null control | %s | %s |\n", ncLabel, ncDetail)
	} else {
		fmt.Fprintf(&b, "| Null control | untested | Run with --null-control to validate signal vs. noise |\n")
	}
	if repResult != nil && len(repResult.Runs) >= 2 {
		repLabel := "partial"
		repDetail := fmt.Sprintf("%d runs, some metrics unstable", len(repResult.Runs))
		if repResult.Stability.AllStable {
			repLabel = "pass"
			repDetail = fmt.Sprintf("%d runs, all CV < 0.2", len(repResult.Runs))
		}
		fmt.Fprintf(&b, "| Replication stability | %s | %s |\n", repLabel, repDetail)
	} else {
		fmt.Fprintf(&b, "| Replication stability | untested | Run with --replicate N to test cross-run stability |\n")
	}
	if scResult != nil {
		passRate := scResult.PassRate() * 100
		scLabel := "pass"
		if passRate < 70 {
			scLabel = "fail"
		} else if passRate < 85 {
			scLabel = "partial"
		}
		fmt.Fprintf(&b, "| Grounding fidelity | %s | %d/%d stance spot-checks passed (%.0f%%) |\n",
			scLabel, scResult.Passed, scResult.Sampled, passRate)
	} else {
		fmt.Fprintf(&b, "| Grounding fidelity | unchecked | Run with --spot-check to verify stances against source quotes |\n")
	}
	b.WriteString("\n")

	// Methodology notes
	b.WriteString("## Methodology Notes\n\n")
	b.WriteString("**Agent construction**: Speaker-derived agents are grounded in T3C's extracted claims and speaker-crux matrix stances. ")
	b.WriteString("Steelman clusters group speakers with ≥70% voting pattern similarity. ")
	b.WriteString("Topic probes group cruxes by T3C topic and investigate deeper disagreements. ")
	b.WriteString("Round 2 agents (bridge, dissent, empty chair) are informed by Round 1 analysis results.\n\n")
	b.WriteString("**Score interpretation**: Crux scores reflect the proportion of *participating synthetic agents* that agree vs. disagree. ")
	fmt.Fprintf(&b, "With %d speaker-derived and %d structural agents, these scores indicate the *topology of the discourse*, not the strength of evidence or real-world expert consensus. ", nSpeakerDerived, nStructural)
	b.WriteString("Ordinal labels are used instead of raw percentages. Scores are reported separately for speaker-derived and structural agents.\n\n")
	b.WriteString("**Multiple comparisons**: This analysis tests multiple cruxes simultaneously without correction for multiple comparisons. ")
	b.WriteString("With 10+ cruxes across a small agent pool, some apparent disagreements may be artefacts of the generation process rather than genuine discourse splits. ")
	b.WriteString("The LLM both generates crux claims and assigns agent stances — a self-referential loop that inflates apparent disagreement patterns.\n\n")
	b.WriteString("**Circularity**: AI-synthesized agents deliberating about AI governance is inherently circular. ")
	b.WriteString("This report maps discourse structure — it does not produce independent evidence. ")
	b.WriteString("Conclusions should be treated as hypotheses to be tested against primary sources and real expert input.\n\n")
	if repResult != nil && len(repResult.Runs) >= 2 {
		fmt.Fprintf(&b, "**Replicability**: This analysis was replicated across %d runs. ", len(repResult.Runs))
		if repResult.Stability.AllStable {
			b.WriteString("Cross-run metrics are stable (CV < 0.2). Findings are reproducible.\n\n")
		} else {
			b.WriteString("Some metrics showed high variance across runs. Findings should be interpreted with caution.\n\n")
		}
	} else {
		b.WriteString("**Replicability**: This is a single pipeline run. LLM outputs are stochastic — a second run on the same input will produce different crux wordings, scores, and topic labels. ")
		b.WriteString("Findings that appear across multiple runs are more robust than single-run results.\n\n")
	}

	// Next steps
	if joinCode != "" || delibID != "" {
		b.WriteString("## Next Steps\n\n")
		if joinCode != "" {
			fmt.Fprintf(&b, "- **Join the deliberation**: `coordinate action:join code:%s`\n", joinCode)
		}
		lastRound := 1
		if r2JSON != "" {
			lastRound = 2
		}
		if r3JSON != "" {
			lastRound = 3
		}
		fmt.Fprintf(&b, "- **Continue deliberating**: submit new positions to extend beyond Round %d\n", lastRound)
		fmt.Fprintf(&b, "- **Generate new compromise**: `analyze action:propose_compromise deliberation_id:%s`\n", delibID)
		b.WriteString("- **Replicate**: run the import again to test stability of findings across runs\n")
		b.WriteString("- **Validate grounding**: spot-check 10-15 agent stances against primary source documents\n")
	}

	return b.String()
}

func writeAnalysis(b *strings.Builder, r *analysisResult, compromise string, nSpeakers, nStructural int) {
	if len(r.Cruxes) > 0 {
		b.WriteString("### Cruxes\n\n")
		for _, c := range r.Cruxes {
			label := controversyLabel(c.Score, len(c.Agree), len(c.Disagree))
			fmt.Fprintf(b, "**[%s]** %s\n", label, c.Claim)

			speakerAgree, structAgree := splitAgentTypes(c.Agree)
			speakerDisagree, structDisagree := splitAgentTypes(c.Disagree)

			// Speaker-only line
			if len(speakerAgree) > 0 || len(speakerDisagree) > 0 {
				b.WriteString("- *Speakers*: ")
				parts := []string{}
				if len(speakerAgree) > 0 {
					parts = append(parts, fmt.Sprintf("Agree: %s", prettyAgentList(speakerAgree)))
				}
				if len(speakerDisagree) > 0 {
					parts = append(parts, fmt.Sprintf("Disagree: %s", prettyAgentList(speakerDisagree)))
				}
				b.WriteString(strings.Join(parts, " | "))
				b.WriteString("\n")
			}
			// Structural line
			if len(structAgree) > 0 || len(structDisagree) > 0 {
				b.WriteString("- *Structural*: ")
				parts := []string{}
				if len(structAgree) > 0 {
					parts = append(parts, fmt.Sprintf("Agree: %s", prettyAgentList(structAgree)))
				}
				if len(structDisagree) > 0 {
					parts = append(parts, fmt.Sprintf("Disagree: %s", prettyAgentList(structDisagree)))
				}
				b.WriteString(strings.Join(parts, " | "))
				b.WriteString("\n")
			}
			b.WriteString("\n")
		}
	}

	// Convergence points
	cleaned := cleanConsensus(r.ConsensusStatements)
	if len(cleaned) > 0 {
		b.WriteString("### Unchallenged Within This Agent Pool\n\n")
		b.WriteString("*Positions on which no synthetic agent registered disagreement. These reflect the topology of this specific agent pool — not established truths or real-world expert consensus.*\n\n")
		for _, cs := range cleaned {
			fmt.Fprintf(b, "- %s\n", cs)
		}
		b.WriteString("\n")
	}

	// Compromise proposal
	if compromise != "" {
		b.WriteString("### Compromise Proposal\n\n")
		b.WriteString("*LLM-generated synthesis — not grounded in specific agent positions. Treat as a starting point, not a conclusion.*\n\n")
		fmt.Fprintf(b, "> %s\n\n", strings.ReplaceAll(compromise, "\n", "\n> "))
	}

	// Topics
	if len(r.TopicSummaries) > 0 {
		b.WriteString("### Topics\n\n")
		for _, ts := range r.TopicSummaries {
			summary := ts.Summary
			if len(summary) > 500 {
				summary = summary[:497] + "..."
			}
			if ts.TopicID != "" {
				fmt.Fprintf(b, "**%s: %s**: %s\n\n", ts.TopicID, ts.Topic, summary)
			} else {
				fmt.Fprintf(b, "**%s**: %s\n\n", ts.Topic, summary)
			}
		}
	}

	// Reliability per-round
	fmt.Fprintf(b, "*Internal coherence: %s (self-assessed, not externally validated)*\n\n", r.Confidence)
}

func splitAgentTypes(agents []string) (speakers, structural []string) {
	for _, a := range agents {
		if isStructuralAgent(a) {
			structural = append(structural, a)
		} else {
			speakers = append(speakers, a)
		}
	}
	return
}

func cleanConsensus(statements []struct{ Content string }) []string {
	var cleaned []string
	for _, cs := range statements {
		lines := strings.Split(cs.Content, "\n")
		var substantive []string
		pastHeader := false
		for _, line := range lines {
			trimmed := strings.TrimSpace(line)
			if !pastHeader {
				if trimmed == "" {
					continue
				}
				upper := strings.ToUpper(trimmed)
				if strings.HasPrefix(upper, "SPEAKER:") ||
					strings.HasPrefix(upper, "STEELMAN") ||
					strings.HasPrefix(upper, "ADVERSARY") ||
					strings.HasPrefix(upper, "PROBE") ||
					strings.HasPrefix(upper, "BRIDGE") ||
					strings.HasPrefix(upper, "DISSENT") ||
					strings.HasPrefix(upper, "EMPTY CHAIR") ||
					strings.HasPrefix(upper, "REVISED POSITION") ||
					strings.HasPrefix(upper, "ROUND ") ||
					strings.HasPrefix(upper, "CRUX") ||
					strings.HasPrefix(upper, "WHAT'S THE ") {
					continue
				}
				pastHeader = true
			}
			if trimmed == "" && len(substantive) == 0 {
				continue
			}
			if strings.HasPrefix(trimmed, "- ") {
				bullet := strings.TrimPrefix(trimmed, "- ")
				bulletUpper := strings.ToUpper(bullet)
				if strings.HasPrefix(bulletUpper, "AGREE:") ||
					strings.HasPrefix(bulletUpper, "DISAGREE:") ||
					strings.HasPrefix(bulletUpper, "SPEAKER:") ||
					strings.HasPrefix(bulletUpper, "STEELMAN") ||
					strings.HasPrefix(bulletUpper, "ROUND ") ||
					strings.HasPrefix(bullet, "What's the ") ||
					strings.HasPrefix(bullet, "Round 1 found") {
					continue
				}
				substantive = append(substantive, bullet)
			} else if trimmed != "" && !strings.HasPrefix(trimmed, "Stances:") &&
				!strings.HasPrefix(trimmed, "Task:") &&
				!strings.HasPrefix(trimmed, "Present the") &&
				!strings.HasPrefix(trimmed, "Probe deeper") &&
				!strings.HasPrefix(trimmed, "Play devil") &&
				!strings.HasPrefix(trimmed, "Build outward") &&
				!strings.HasPrefix(trimmed, "AGREE:") &&
				!strings.HasPrefix(trimmed, "DISAGREE:") &&
				!strings.HasPrefix(trimmed, "Round 1 found") &&
				!strings.HasPrefix(trimmed, "What's the strongest") {
				substantive = append(substantive, trimmed)
			}
		}
		for _, s := range substantive {
			if len(s) <= 10 {
				continue
			}
			last := s[len(s)-1]
			if last != '.' && last != '!' && last != '?' && last != ')' && last != '"' {
				continue
			}
			cleaned = append(cleaned, s)
		}
	}
	return cleaned
}

var acronyms = map[string]string{
	"ai": "AI", "agi": "AGI", "llm": "LLM", "api": "API",
}

func prettyAgentList(agents []string) string {
	if len(agents) == 0 {
		return "(none)"
	}
	names := make([]string, len(agents))
	for i, a := range agents {
		a = strings.TrimPrefix(a, "t3c-")
		if strings.HasPrefix(a, "empty-chair-") {
			num := strings.TrimPrefix(a, "empty-chair-")
			n := 0
			fmt.Sscanf(num, "%d", &n)
			names[i] = fmt.Sprintf("Empty Chair %d", n+1)
			continue
		}
		a = strings.TrimPrefix(a, "speaker-")
		a = strings.TrimPrefix(a, "steelman-")
		a = strings.TrimPrefix(a, "probe-")
		a = strings.TrimPrefix(a, "adversary-")
		a = strings.TrimPrefix(a, "resolution-")
		a = strings.ReplaceAll(a, "-", " ")
		words := strings.Fields(a)
		for j, w := range words {
			if upper, ok := acronyms[strings.ToLower(w)]; ok {
				words[j] = upper
			} else if len(w) > 0 {
				words[j] = strings.ToUpper(w[:1]) + w[1:]
			}
		}
		names[i] = strings.Join(words, " ")
	}
	return strings.Join(names, ", ")
}

func firstLine(s string) string {
	// Skip header lines (SPEAKER:, STEELMAN, REVISED POSITION, etc.)
	for _, line := range strings.Split(s, "\n") {
		trimmed := strings.TrimSpace(line)
		if trimmed == "" {
			continue
		}
		upper := strings.ToUpper(trimmed)
		if strings.HasPrefix(upper, "SPEAKER:") || strings.HasPrefix(upper, "STEELMAN") ||
			strings.HasPrefix(upper, "REVISED POSITION") || strings.HasPrefix(upper, "PROBE") {
			continue
		}
		if len(trimmed) > 120 {
			return trimmed[:117] + "..."
		}
		return trimmed
	}
	if len(s) > 120 {
		return s[:117] + "..."
	}
	return s
}

func metricDelta(real, null int) string {
	if real == 0 {
		if null == 0 {
			return "—"
		}
		return fmt.Sprintf("%+d", null-real)
	}
	pct := float64(real-null) / float64(real) * 100
	return fmt.Sprintf("%+.0f%%", pct)
}

func metricDeltaFloat(real, null float64) string {
	if real == 0 {
		if null == 0 {
			return "—"
		}
		return fmt.Sprintf("%+.2f", real-null)
	}
	pct := (real - null) / real * 100
	return fmt.Sprintf("%+.0f%%", pct)
}

type cruxInfo struct {
	Claim     string
	Score     float64
	NAgree    int
	NDisagree int
}

func findNewCruxes(r1, r2 []struct {
	Claim    string   `json:"crux_claim"`
	Agree    []string `json:"agree_agents"`
	Disagree []string `json:"disagree_agents"`
	Score    float64  `json:"controversy_score"`
}) []cruxInfo {
	r1Claims := map[string]bool{}
	for _, c := range r1 {
		r1Claims[c.Claim] = true
	}
	var newOnes []cruxInfo
	for _, c := range r2 {
		if !r1Claims[c.Claim] {
			newOnes = append(newOnes, cruxInfo{Claim: c.Claim, Score: c.Score, NAgree: len(c.Agree), NDisagree: len(c.Disagree)})
		}
	}
	return newOnes
}
